In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
df = pd.read_csv('Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

**Figureout which one is independent and which is dependent(Purchased) variable**

In [4]:
# This will add all the rows using and will include all the columns except last one.
X = df.iloc[:, :-1].values

# This will add all the rows and only last column
y = df.iloc[:, -1].values

X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [5]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [6]:
missing = df.isnull() # Will check all the null values
missing_counts = missing.sum() # Will sum up all the null values and will display number
missing_counts

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

**Taking care of missing data**

In [7]:
from sklearn.impute import SimpleImputer 

imputer = SimpleImputer(missing_values=np.nan, strategy="mean") # Creating class instance to calculate the mean

In [8]:
imputer.fit(X[:, 1:3]) # Will fit the data into instance, will perform mean operation on the data
X[:, 1:3] = imputer.transform(X[:, 1:3]) # Will change the data into field
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

### Encoding the categorical data to numbers using OneHotEncoding

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')

In [10]:
X = np.array(ct.fit_transform(X))
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

**Encoding dependent variable**

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2)

In [14]:
X_train

array([[0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [15]:
X_test

array([[0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0]], dtype=object)

In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [17]:
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])

In [18]:
X_train

array([[0.0, 1.0, 0.0, 1.8005953365467893, 1.9275299694293098],
       [0.0, 1.0, 0.0, -1.1094577326197388, -0.916768670972385],
       [1.0, 0.0, 0.0, 0.9275794157968308, 0.8486580713459083],
       [0.0, 0.0, 1.0, 0.054563495046872405, -0.2302138267374932],
       [0.0, 0.0, 1.0, -1.545965692994718, -1.5052442517451496],
       [1.0, 0.0, 0.0, -0.090939158411454, 0.3582617540352713],
       [0.0, 1.0, 0.0, 0.34556880196352524, 0.0422285717684166],
       [1.0, 0.0, 0.0, -0.38194446532810683, -0.5244516171238754]],
      dtype=object)

In [20]:
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [21]:
X_test

array([[0.0, 0.0, 1.0, 0.1677322255144597, -1.11292719789664],
       [1.0, 0.0, 0.0, 1.5095900296301366, 1.5352129155808003]],
      dtype=object)